apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-mongo-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-mongo-api
  template:
    metadata:
      labels:
        app: express-mongo-api
    spec:
      containers:
      - name: express-mongo-api
        image: gcr.io/peerless-list-423401-k1/express-mongo-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: evms-api-config
              key: DB_SERVER_NAME
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: express-mongo-api-service
spec:
  type: LoadBalancer
  selector:
    app: express-mongo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
